---
rpm_keys:
  - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
  - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
  - "https://packages.microsoft.com/keys/microsoft.asc"

remove_packages:
  - totem
  - rhythmbox
  - cheese
  - gnome-boxes

install_packages:
  - '@multimedia' # Installed with fusion repo
  - code # Installed with vscode repo
  - '@virtualization'
  - syncthing
  - android-tools
  - fish
  - git-credential-libsecret
  - docker-compose
  - usbguard
  - snapper