---
- name: Run the equivalent of "pacman -Syu"
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install core packages
  community.general.pacman:
    name: "{{ core_packages }}"
