---
- hosts: localhost
  connection: local

  tasks:
    # This role will install the packages needed for the system to work properly as well as configure local and other files.
    # It will also generate the kernel and the bootloader.
    - name: (LIVE) Core configuration & core installation
      ansible.builtin.import_role:
        name: 00-core
      become: true
      become_user: root
      tags:
        - LIVE
        - 00-core

    # This role will install and configure the necessary packages for a standard desktop computer.
    - name: (LIVE) System configuration & system installation
      ansible.builtin.import_role:
        name: 01-system
      become: true
      become_user: root
      tags:
        - LIVE
        - 01-system

    # This role will create and configure an user.
    - name: (ROOT) User configuration
      ansible.builtin.import_role:
        name: 02-users
      become: true
      become_user: root
      tags:
        - ROOT
        - 02-users

    # This role will install a desktop environment for the user and start systemd services.
    - name: (ROOT) Desktop configuration & start of services
      ansible.builtin.import_role:
        name: 03-desktop
      become: true
      become_user: root
      tags:
        - ROOT
        - 03-desktop

    # This role will install the software at the user level (flatpak) and install its configuration files.
    - name: (USER) Dotfiles installation
      ansible.builtin.import_role:
        name: 04-homedir
      become: true
      become_user: "{{ user.name }}"
      tags:
        - USER
        - 04-homedir
