---
- hosts: localhost
  gather_facts: yes

  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: system/packages
      become: true
      when: ansible_distribution == 'Fedora'
      tags: SYSTEM,packages

    - name: Install flatpak
      ansible.builtin.import_role:
        name: system/flatpak
      become: true
      tags: SYSTEM,flatpak

    - name: Configure the system
      ansible.builtin.import_role:
        name: system/config
      become: true
      tags: SYSTEM,config
    
    - name: Hardened the system
      ansible.builtin.import_role:
        name: system/security
      become: true
      tags: SYSTEM,security

    - name: Configure users
      ansible.builtin.import_role:
        name: system/users
      become: true
      tags: SYSTEM,users

    - name: Enable services
      ansible.builtin.import_role:
        name: user/services
      become: false
      tags: USER,services

    - name: Install dotfiles
      ansible.builtin.import_role:
        name: user/dotfiles
      become: false
      tags: USER,dotfiles
  
    - name: Configure Gnome
      ansible.builtin.import_role:
        name: user/gnome
      become: false
      tags: USER,gnome
