---
- hosts: localhost
  connection: local

  tasks:
    # This role will install the packages needed for the system to work properly as well as configure local and other files.
    # It will also generate the kernel and the bootloader.
    - name: Core configuration & core installation
      ansible.builtin.import_role:
        name: 00-core
      tags:
        - LIVE
        - 00-core

    # This role will install important packages and configure the system
    - name: System configuration & system installation
      ansible.builtin.import_role:
        name: 01-system
      tags:
        - LIVE
        - 01-system

    # This role will install a desktop environment for the user and configure some apps
    - name: Desktop configuration & start of services
      ansible.builtin.import_role:
        name: 02-desktop
      tags:
        - BOOT
        - 02-desktop

    # This role will create and configure an user.
    - name: User configuration
      ansible.builtin.import_role:
        name: 03-users
      tags:
        - BOOT
        - 03-users

    # This role will install the software at the user level (flatpak) and install dotfiles.
    - name: Dotfiles installation
      ansible.builtin.import_role:
        name: 04-homedir
      tags:
        - BOOT
        - 04-homedir

    # This role will start every Systemd services
    - name: Systemd services installation
      ansible.builtin.import_role:
        name: 05-services
      tags:
        - BOOT
        - 05-services
