---
- hosts: localhost
  connection: local

  tasks:
    # This role will install the packages needed for the system to work properly
    - name: Core configuration & core installation
      ansible.builtin.import_role:
        name: 00-core
      tags:
        - LIVE
        - 00-core

    # This role will install important packages and configure the system
    - name: System configuration & system installation
      ansible.builtin.import_role:
        name: 01-system
      tags:
        - LIVE
        - 01-system

    # This role will install a desktop environment for the user and start services
    - name: Desktop configuration & start of services
      ansible.builtin.import_role:
        name: 02-desktop
      tags:
        - BOOT
        - 02-desktop

    # This role will install and configure applications
    - name: User configuration
      ansible.builtin.import_role:
        name: 03-applications
      tags:
        - BOOT
        - 03-applications

    # This role will create and configure an user
    - name: User configuration
      ansible.builtin.import_role:
        name: 04-users
      tags:
        - BOOT
        - 04-users

    # This role will install the software at the user level (flatpak) and install dotfiles
    - name: Dotfiles installation
      ansible.builtin.import_role:
        name: 05-homedir
      tags:
        - BOOT
        - 05-homedir
