---
- hosts: localhost
  gather_facts: yes

  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: packages
      become: true
      tags: packages

    - name: Install flatpak
      ansible.builtin.import_role:
        name: flatpak
      become: true
      tags: flatpak

    - name: Configure the system
      ansible.builtin.import_role:
        name: system
      become: true
      tags: system

    - name: Configure users
      ansible.builtin.import_role:
        name: users
      become: true
      tags: users
    
    - name: Hardened the system
      ansible.builtin.import_role:
        name: security
      become: true
      tags: security

    - name: Enable services
      ansible.builtin.import_role:
        name: services
      # Become is set at the task level
      tags: services

    - name: Install dotfiles
      ansible.builtin.import_role:
        name: dotfiles
      become: false
      tags: dotfiles
  
    - name: Configure desktop
      ansible.builtin.import_role:
        name: desktop
      become: false
      tags: desktop