---
- hosts: localhost
  gather_facts: yes

  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: system/packages
      become: true
      tags: system,packages

    - name: Install flatpak
      ansible.builtin.import_role:
        name: system/flatpak
      become: true
      tags: system,flatpak

    - name: Configure the system
      ansible.builtin.import_role:
        name: system/configuration
      become: true
      tags: system,configuration
    
    - name: Hardened the system
      ansible.builtin.import_role:
        name: system/security
      become: true
      tags: system,security

    - name: Configure users
      ansible.builtin.import_role:
        name: system/accounts
      become: true
      tags: system,accounts

    - name: Enable services
      ansible.builtin.import_role:
        name: user/services
      become: false
      tags: user,services

    - name: Install dotfiles
      ansible.builtin.import_role:
        name: user/dotfiles
      become: false
      tags: user,dotfiles
  
    - name: Configure Gnome
      ansible.builtin.import_role:
        name: user/gnome
      become: false
      tags: user,gnome