---
- hosts: localhost
  connection: local

  tasks:
    - name: Core configuration & core installation
      ansible.builtin.import_role:
        name: 00-core
      tags:
        - LIVE
        - 00-core

    - name: System configuration & system installation
      ansible.builtin.import_role:
        name: 01-system
      tags:
        - LIVE
        - 01-system

    - name: Desktop configuration & start of services
      ansible.builtin.import_role:
        name: 02-desktop
      tags:
        - BOOT
        - 02-desktop

    - name: User configuration
      ansible.builtin.import_role:
        name: 03-applications
      tags:
        - BOOT
        - 03-applications

    - name: User configuration
      ansible.builtin.import_role:
        name: 04-access
      tags:
        - BOOT
        - 04-access

    - name: Dotfiles installation
      ansible.builtin.import_role:
        name: 05-homedir
      tags:
        - HOME
        - 05-homedir
