---
- hosts: localhost
  gather_facts: yes

  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: system/packages
      become: true
      tags: SYSTEM,packages

    - name: Install flatpak
      ansible.builtin.import_role:
        name: system/flatpak
      become: true
      tags: SYSTEM,flatpak

    - name: Configure the system
      ansible.builtin.import_role:
        name: system/configuration
      become: true
      tags: SYSTEM,configuration
    
    - name: Hardened the system
      ansible.builtin.import_role:
        name: system/security
      become: true
      tags: SYSTEM,security

    - name: Enable system services
      ansible.builtin.import_role:
        name: system/services
      become: true
      tags: SYSTEM,services

    - name: Enable user services
      ansible.builtin.import_role:
        name: user/services
      become: false
      tags: USER,services

    - name: Install dotfiles
      ansible.builtin.import_role:
        name: user/dotfiles
      become: false
      tags: USER,dotfiles
  
    - name: Configure desktop
      ansible.builtin.import_role:
        name: user/desktop
      become: false
      tags: USER,desktop