---
- ansible.builtin.import_tasks: dconf.yml
  tags: desktop,dconf

- ansible.builtin.import_tasks: font.yml
  tags: desktop,font

- ansible.builtin.import_tasks: antimicrox.yml
  become: true
  tags: desktop,antimicrox