---
- name: Check that user exist
  ansible.builtin.getent:
    database: passwd
    key: "{{ item }}"
    fail_key: false
  loop: "{{ users.keys() | list }}"

- name: Configure users
  ansible.builtin.user:
    name: "{{ item }}"
    comment: "{{ users[item].comment }}"
    groups: "{{ users[item].groups }}"
    shell: "{{ users[item].shell }}"
    state: present
  when: item not in getent_passwd.keys()
  loop: "{{ users.keys() | list }}"
