---
- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages.rpm }}"
    state: present
    skip_broken: true
    allowerasing: true

- name: Autoremove unneeded packages
  ansible.builtin.dnf:
    autoremove: yes