---
- name: Install traditional packages & resolve dependencies
  ansible.builtin.dnf:
    name: "{{ traditional_packages }}"
    allowerasing: false
    state: present


- name: Install RPM Fusion packages & resolve dependencies
  ansible.builtin.dnf:
    name: "{{ fusion_packages }}"
    allowerasing: true
    state: present

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: yes