---
- name: Install traditional packages
  ansible.builtin.dnf:
    name: "{{ rpm_packages }}"
    state: present
    allowerasing: true

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: yes