---
- name: Import RPM keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ fusion_keys }}"

- name: Add RPM Fusion repositories
  ansible.builtin.dnf:
    name: "{{ fusion_repositories }}"
    state: present

- name: Install RPM Fusion packages
  ansible.builtin.dnf:
    name: "{{ fusion_packages }}"
    state: present
    allowerasing: true

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: yes