---
- ansible.builtin.import_tasks: repositories.yml
  tags: rpm,repositories

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages.rpm }}"
    state: present
    skip_broken: true
    allowerasing: true
  tags: rpm,packages

- name: Autoremove unneeded packages
  ansible.builtin.dnf:
    autoremove: yes
  tags: rpm,packages