---
- name: Add Fusion repositories
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Add VSCode repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/vscode.repo
    content: |
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey={{ rpm_keys[0] }}
    force: true