---
- name: Add Fusion repositories
  ansible.builtin.dnf:
    name: "{{ fusion_repositories }}"
    state: present

- name: Add VSCode repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/vscode.repo
    content: |
      [code]
      name=Visual Studio Code
      baseurl={{ vscode_url }}
      enabled=1
      gpgcheck=1
      gpgkey={{ rpm_keys[0] }}
    force: true