---
- name: Import RPM keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - "{{ rpmfusion_free_key }}"
    - "{{ rpmfusion_nonfree_key }}"

- name: Add additional repositories
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ rpmfusion_free_repository }}"
    - "{{ rpmfusion_nonfree_repository }}"