---
- name: Import RPM keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ rpm_keys }}"

- name: Add RPM Fusion repositories
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Add Mullvad repository
  ansible.builtin.yum_repository:
    name: mullvad-stable
    description: Mullvad VPN
    baseurl: https://repository.mullvad.net/rpm/stable/$basearch
    gpgkey: "{{ rpm_keys[2] }}"
    gpgcheck: true

- name: Add VSCode repository
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: "{{ rpm_keys[3] }}"
    gpgcheck: true