---
- name: Download Fira Code Nerd Font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
    dest: /tmp/FiraCode.zip

- name: ensure font dir exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.local/share/fonts/fira-code"
    recurse: true
    state: directory

- name: Extract Fira Code Nerd Font
  ansible.builtin.unarchive:
    src: /tmp/FiraCode.zip
    dest: "/home/{{ ansible_user_id }}/.local/share/fonts/fira-code"

- name: Clean /tmp from Fira Code
  ansible.builtin.file:
    path: /tmp/FiraCode.zip
    state: absent