---
additionnal_packages:
  # Connection
  - syncthing
  - android-tools

  # Podman
  - docker-compose

  # Git
  - git-credential-libsecret

  # Ansible
  - ansible

  # Shell
  - fish

  # Appearance
  - papirus-icon-theme