---
- name: Add user
  ansible.builtin.user:
    name: "{{ user.name }}"
    comment: "{{ user.comment }}"
    password: "{{ user.password | password_hash }}"
    groups: "{{ user.groups }}"
    shell: "{{ user.shell }}"
    home: "/home/{{ user.name }}"
    state: present