---
- name: Set default zone to public
  ansible.builtin.command: firewall-cmd --set-default-zone=public

- name: Enable services in home zone
  ansible.posix.firewalld:
    service: syncthing
    zone: home
    permanent: true
    immediate: true
    state: enabled