---
terminal_packages:
  # Terminal
  - fish
  - htop
  - ranger
  - atool
  - calcurse

  # Development
  - neovim
  - npm
  - python-pip
  - android-tools

  # Libraries
  - python-i3ipc
  - python-psutil

desktop_packages:
  # Desktop
  - sway
  - swaybg
  - swayidle
  - swaylock

  # Status bar
  - waybar

  # Notification
  - dunst
  - libnotify

  # Output
  - gammastep
  - brightnessctl

  # Screenshot
  - grim
  - slurp

  # Menu & Terminal
  - fuzzel
  - kitty

  # Extra
  - wl-clipboard
  - gnome-keyring
  - polkit-kde-agent

  # X11
  - xsettingsd
  - xorg-xwayland

  # XDG
  - xdg-utils
  - xdg-user-dirs
  - xdg-desktop-portal-wlr

applications_packages:
  - wireshark-qt

  # Files
  - thunar
  - gvfs-mtp
  - gvfs-smb

  # Appearance
  - papirus-icon-theme

font_packages:
  - ttf-jetbrains-mono-nerd
  - ttf-liberation
  - ttf-dejavu
  - noto-fonts
  - noto-fonts-emoji

systemd_services:
  - systemd-timesyncd.service
  - systemd-resolved.service
  - bluetooth.service
  - firewalld.service
  - NetworkManager.service
  - cups.service
  - auditd.service
  - apparmor.service
  - usbguard.service
  - power-profiles-daemon.service
