---
flathub_packages:
  # Tools
  - com.mattjakeman.ExtensionManager
  - ca.desrt.dconf-editor
  - com.github.tchx84.Flatseal
  - org.gnome.seahorse.Application

  # Multimedia
  - org.videolan.VLC

  # Chat
  - com.discordapp.Discord

  # Personal
  - org.keepassxc.KeePassXC
  - md.obsidian.Obsidian

  # Gaming
  - com.valvesoftware.Steam
  - com.mojang.Minecraft
  - sh.ppy.osu
  - net.lutris.Lutris