---
- name: Install terminal packages
  community.general.pacman:
    name: "{{ terminal_packages }}"
    state: present

- name: Install applications packages
  community.general.pacman:
    name: "{{ applications_packages }}"
    state: present
