---
- name: Get file information
  ansible.builtin.stat:
    path: /etc/usbguard/rules.conf
  register: file_info

- name: Generate USBGuard rules
  ansible.builtin.command: bash -c "usbguard generate-policy > /etc/usbguard/rules.conf"
  when: file_info.stat.size == 0

- name: Add wheel group to usbguard
  ansible.builtin.lineinfile:
    path: /etc/usbguard/usbguard-daemon.conf
    state: present
    regexp: '^IPCAllowedGroups='
    line: "IPCAllowedGroups=wheel"

- name: Restart Usbguard service
  ansible.builtin.service:
    name: usbguard.service
    state: restarted
