---
- name: Generate USBGuard rules
  ansible.builtin.command: bash -c "usbguard generate-policy > /etc/usbguard/rules.conf"

- name: Add wheel group to usbguard
  ansible.builtin.lineinfile:
    path: /etc/usbguard/usbguard-daemon.conf
    state: present
    regexp: '^IPCAllowedGroups='
    line: "IPCAllowedGroups=wheel"

- name: Restart Usbguard service
  ansible.builtin.service:
    name: usbguard.service
    state: restarted
