---
kernel: linux-hardened
esp_dir: /boot
timezone: Europe/Paris
locale: en_US.UTF-8
keymap: fr
hostname: blue-duck

core_packages:
  - base
  - base-devel
  - "{{ kernel }}"
  - linux-firmware
  - pacman-contrib
  - intel-ucode
  - apparmor
  - btrfs-progs
  - ntfs-3g
  - zip
  - unzip
  - unrar
  - p7zip
  - git
  - wget
