---
rpm_keys:
  - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
  - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"

rpm_repositories:
  - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

unwanted_packages:
  - totem
  - gnome-photos
  - rhythmbox
  - firefox

wanted_packages:
  - syncthing
  - android-tools
  - git-credential-libsecret
  - fish
  - docker-compose
  - usbguard
  - snapper