---
- name: Clone user dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/kaniville/linux-dotfiles.git'
    dest: /tmp/dotfiles
    clone: true
    update: true

- name: Install user dotfiles
  ansible.posix.synchronize:
    src: /tmp/dotfiles/
    dest: "/home/{{ user.name }}"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=src"
      - "--exclude=LICENSE"
      - "--exclude=README.md"

- name: Install Fisher
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    dest: "/home/{{ user.name }}/.config/fish/functions/fisher.fish"
