---
- name: Install AUR helper
  kewlfft.aur.aur:
    use: makepkg
    name: yay
    state: present
  become_user: "{{ user.name }}"

- name: Install AUR packages
  kewlfft.aur.aur:
    use: yay
    name: "{{ aur_packages }}"
    state: present
  become_user: "{{ user.name }}"
