---
- name: Enable tlp service
  ansible.builtin.systemd:
    name: tlp.service
    state: started
    enabled: true

- name: Enable apparmor service
  ansible.builtin.systemd:
    name: apparmor.service
    state: started
    enabled: true

- name: Enable firewalld service
  ansible.builtin.systemd:
    name: firewalld.service
    state: started
    enabled: true

- name: Enable NetworkManager service
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: started
    enabled: true

- name: Enable bluetooth service
  ansible.builtin.systemd:
    name: bluetooth.service
    state: started
    enabled: true

- name: Enable cups service
  ansible.builtin.systemd:
    name: cups.service
    state: started
    enabled: true

- name: Enable podman
  ansible.builtin.systemd:
    name: podman.service
    state: started
    enabled: true
    scope: user
  become_user: "{{ user.name }}"
