---
- name: Import the packages
  ansible.builtin.import_tasks:
    file: packages.yml
  tags: packages

- name: Import the services
  ansible.builtin.import_tasks:
    file: services.yml
  tags: services

- name: Import apparmor profiles
  ansible.builtin.import_tasks:
    file: apparmor.yml
  tags: security
