---
- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/share/doc/android-tools/51-android.rules
    dest: /etc/udev/rules.d/51-android.rules
    state: link

- name: Ensure group "adbusers" exists
  ansible.builtin.group:
    name: adbusers
    state: present