---
- ansible.builtin.import_tasks: adb.yml
  tags: system.adb

- ansible.builtin.import_tasks: sysctl.yml
  tags: system.sysctl

- ansible.builtin.import_tasks: hostname.yml
  tags: system.hostname

- ansible.builtin.import_tasks: user.yml
  tags: system.user