---
- ansible.builtin.import_tasks: sysctl.yml
  tags: system,sysctl
  become: true

- ansible.builtin.import_tasks: hostname.yml
  tags: system,hostname
  when: hostname is defined
  become: true

- ansible.builtin.import_tasks: firewalld.yml
  tags: system,firewalld
  become: true

- ansible.builtin.import_tasks: selinux.yml
  tags: system,selinux
  become: true