---
- ansible.builtin.import_tasks: sysctl.yml
  tags: sysctl

- ansible.builtin.import_tasks: hostname.yml
  tags: hostname

- ansible.builtin.import_tasks: user.yml
  tags: user

- ansible.builtin.import_tasks: firewalld.yml
  tags: firewalld

- ansible.builtin.import_tasks: selinux.yml
  tags: selinux