flatpak_packages:
  - org.gnome.eog
  - org.gnome.Evince
  - org.gnome.Calculator
  - org.gnome.FileRoller
  - org.gnome.seahorse.Application
  - org.mozilla.firefox
  - org.chromium.Chromium
  - org.libreoffice.LibreOffice
  - org.gimp.GIMP
  - org.keepassxc.KeePassXC
  - org.filezillaproject.Filezilla
  - org.guitarix.Guitarix
  - org.rncbc.qpwgraph
  - com.github.tchx84.Flatseal
  - com.valvesoftware.Steam
  - com.mojang.Minecraft
  - com.spotify.Client
  - com.discordapp.Discord
  - com.usebottles.bottles
  - sh.ppy.osu
  - io.mpv.Mpv
