---
- name: Get explicitely installed packages
  ansible.builtin.command: pacman -Qeq
  register: explicit_packages

- name: Convert output to list
  ansible.builtin.set_fact:
    explicit_packages: "{{ explicit_packages.stdout_lines }}"

- name: Compare installed packages
  ansible.builtin.set_fact:
    explicit_packages: "{{ explicit_packages | difference(vars[item]) }}"
  loop:
    - core_packages
    - system_packages
    - desktop_packages
    - applications_packages
    - font_packages

- name: Remove packages
  community.general.pacman:
    name: "{{ explicit_packages }}"
    state: absent
  when: explicit_packages | length > 0
