---
flatpak_packages:
  # Media
  - org.gnome.Loupe
  - org.videolan.VLC

  # System
  - com.mattjakeman.ExtensionManager
  - ca.desrt.dconf-editor
  - com.github.tchx84.Flatseal
  - org.gnome.seahorse.Application

  # Tools
  - org.onlyoffice.desktopeditors
  - org.gimp.GIMP
  - org.keepassxc.KeePassXC
  - md.obsidian.Obsidian

  # Games
  - com.valvesoftware.Steam
  - com.mojang.Minecraft
  - sh.ppy.osu

  # Internet
  - org.mozilla.firefox
  - com.discordapp.Discord

  # Development
  - com.visualstudio.code
  - com.visualstudio.code.tool.podman

user_services:
  - podman.service
  - syncthing.service
