---
flatpak_packages:
  # Media
  - org.gnome.Loupe
  - org.videolan.VLC
  - io.bassi.Amberol

  # System
  - com.mattjakeman.ExtensionManager
  - ca.desrt.dconf-editor
  - com.github.tchx84.Flatseal
  - org.gnome.seahorse.Application

  # Tools
  - org.onlyoffice.desktopeditors
  - org.gimp.GIMP
  - org.keepassxc.KeePassXC
  - md.obsidian.Obsidian
  - org.gnome.TextEditor

  # Games
  - com.valvesoftware.Steam
  - com.mojang.Minecraft
  - sh.ppy.osu

  # Web browser
  - org.mozilla.firefox

  # Chat
  - com.discordapp.Discord

user_services:
  - podman.service
  - syncthing.service
