---
- name: Add users
  ansible.builtin.user:
    name: "{{ item }}"
    comment: "{{ users[item].comment }}"
    password: "{{ users[item].password | password_hash }}"
    groups: "{{ users[item].groups }}"
    shell: "{{ users[item].shell }}"
    state: present
  loop: "{{ users.keys() | list }}"