---
- name: Set root account
  ansible.builtin.user:
    name: root
    password: "{{ root_user.password | password_hash }}"
    shell: "{{ root_user.shell }}"
    password_lock: "{{ root_user.lock }}"

- name: Add users
  ansible.builtin.user:
    name: "{{ item }}"
    comment: "{{ users[item].comment }}"
    password: "{{ users[item].password | password_hash }}"
    groups: "{{ users[item].groups }}"
    shell: "{{ users[item].shell }}"
    state: present
  loop: "{{ users.keys() | list }}"