---
system_packages:
  # Administration
  - apparmor
  - usbguard
  - firewalld
  - arch-audit
  - fwupd

  # Networking
  - networkmanager

  # Bluetooth
  - bluez
  - bluez-utils

  # Multimedia
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - wireplumber

  # Virtualization
  - podman
  - podman-compose
  - fuse-overlayfs
  - aardvark-dns
  - distrobox

  # Printing
  - cups
  - ghostscript

  # Disk
  - udisks2

  # Flatpak
  - flatpak
