---
- name: Copy hooks files
  ansible.builtin.copy:
    src: pacman.d/hooks/
    dest: /etc/pacman.d/hooks

- name: Copy hooks scripts
  ansible.builtin.copy:
    src: pacman.d/hooks.bin/
    dest: /etc/pacman.d/hooks.bin
