---
- name: Import packages
  ansible.builtin.import_tasks:
    file: packages.yml
  tags:
    - chroot
    - packages

- name: Import flatpak
  ansible.builtin.import_tasks:
    file: flatpak.yml
  tags:
    - chroot
    - flatpak

- name: Import services
  ansible.builtin.import_tasks:
    file: services.yml
  tags: services

- name: Import AUR
  ansible.builtin.import_tasks:
    file: aur.yml
  tags: aur

- name: Import sudoers
  ansible.builtin.import_tasks:
    file: sudoers.yml
  tags: sudo

- name: Import usbguard
  ansible.builtin.import_tasks:
    file: usbguard.yml
  tags: usbguard
