---
- name: Enable tlp service
  ansible.builtin.systemd:
    name: tlp.service
    state: started
    enabled: true

- name: Enable docker service
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true

- name: Enable cups service
  ansible.builtin.systemd:
    name: cups.service
    state: started
    enabled: true
