---
- name: Clone BTRFS-snapman
  ansible.builtin.git:
    repo: https://github.com/Kaniville/btrfs-snapman
    dest: /tmp/btrfs-snapman
    clone: yes
    update: yes

- name: Copy hook file
  ansible.builtin.copy:
    src: /tmp/btrfs-snapman/snapman.hook
    dest: /etc/pacman.d/hooks/
    force: yes

- name: Copy configuration file
  ansible.builtin.copy:
    src: /tmp/btrfs-snapman/snapman.conf
    dest: /etc/snapman/
    force: yes

- name: Copy script
  ansible.builtin.copy:
    src: /tmp/btrfs-snapman/snapman.py
    dest: /usr/local/bin/snapman
    mode: '0755'
