---
- name: Configure users
  ansible.builtin.user:
    name: "{{ item }}"
    comment: "{{ users[item].comment }}"
    groups: "{{ users[item].groups }}"
    shell: "{{ users[item].shell }}"
    state: present
  loop: "{{ users.keys() | list }}"