---
- name: Install systemd-boot
  ansible.builtin.command: bootctl install
  ignore_errors: true

- name: Create bootloader configuration
  ansible.builtin.copy:
    dest: /boot/loader/loader.conf
    content: |
      default archlinux.conf
      timeout 3
      console-mode keep
      editor no
    force: true

- name: Create bootloader entries
  ansible.builtin.copy:
    dest: /boot/loader/entries/archlinux.conf
    content: |
      title Arch Linux
      linux vmlinuz-linux-hardened
      initrd intel-ucode.img
      initrd initramfs-linux-hardened.img
      options {{ kernel.options }}
    force: true
