---
- name: Check if BOOTX64 exist
  ansible.builtin.stat:
    path: /boot/EFI/BOOT/BOOTX64.EFI
  register: boot_efi

- name: Install systemd-boot
  ansible.builtin.command: bootctl install
  ignore_errors: true
  when: not boot_efi.stat.exists

- name: Create bootloader configuration
  ansible.builtin.copy:
    dest: /boot/loader/loader.conf
    content: |
      default archlinux.conf
      timeout 3
      console-mode keep
      editor no
    force: true

- name: Create bootloader entries
  ansible.builtin.copy:
    dest: /boot/loader/entries/archlinux.conf
    content: |
      title Arch Linux
      linux vmlinuz-{{ kernel.name }}
      initrd intel-ucode.img
      initrd initramfs-{{ kernel.name }}.img
      options {{ kernel.options }}
    force: true
