---
- name: add flathub remote (system)
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: system

- name: Install flatpak packages (system)
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
    method: system
