---
- name: Import packages
  ansible.builtin.import_tasks:
    file: packages.yml
  tags: packages

- name: Import flatpak
  ansible.builtin.import_tasks:
    file: flatpak.yml
  tags: packages

- name: Import dotfiles
  ansible.builtin.import_tasks:
    file: dotfiles.yml
  tags: dotfiles
