---
- name: Enable GDM service
  ansible.builtin.systemd:
    name: gdm.service
    state: started
    enabled: true

- name: Enable power-profile-daemon service
  ansible.builtin.systemd:
    name: power-profiles-daemon.service
    state: started
    enabled: true
