---
- name: ensure Fish dir exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.config/fish/functions"
    recurse: true
    state: directory

- name: Copy Fish configuration
  ansible.builtin.copy:
    src: fish
    dest: "/home/{{ ansible_user_id }}/.config"
    force: true

- name: Install Fisher
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    dest: "/home/{{ ansible_user_id }}/.config/fish/functions/fisher.fish"