---
- name: Add user with systemd-homed
  community.general.homectl:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    memberof: "{{ user.groups }}"
    shell: "{{ user.shell }}"
    storage: "{{ user.storage }}"
    language: "{{ user.language }}"
    timezone: "{{ user.timezone }}"
