---
- name: Add user
  ansible.builtin.user:
    name: "{{ user.name }}"
    comment: "{{ user.comment }}"
    password: "{{ user.password }}"
    groups: "{{ user.groups }}"
    shell: "{{ user.shell }}"
    state: present
