---
- name: Check if systemd-boot is installed
  stat:
    path: {{ esp_dir }}/EFI/BOOT/BOOTX64.EFI
  register: boot_efi

- name: Install systemd-boot
  command: bootctl install
  when: not boot_efi.stat.exists

- name: Create bootloader entries
  ansible.builtin.copy:
    src: loader/
    dest: {{ esp_dir }}/loader
