---
- name: Install systemd-boot
  command: "bootctl install --esp-path={{ esp_path }}"
  args:
    creates: "{{ esp_path }}/EFI/BOOT/BOOTX64.EFI"

- name: Create bootloader entries
  ansible.builtin.copy:
    src: loader/
    dest: "{{ esp_path }}/loader"
