---
- name: Create mkinitcpio config
  ansible.builtin.copy:
    src: mkinitcpio.conf
    dest: /etc/mkinitcpio.conf

- name: Run mkinitcpio
  command: "mkinitcpio -p {{ kernel }}"
  args:
    creates: "/boot/initramfs-{{ kernel }}.img"
