---
- name: Ensure locales are installed
  community.general.locale_gen:
    name: "{{ locale.lang }}"
    state: present

- name: Set locale
  command: "localectl set-locale LANG={{ locale.lang }}"

- name: Set keymap
  command: "localectl set-keymap {{ locale.keymap }}"
