---
- name: Install locales
  locale_gen:
    name: "{{ locale }}"

- name: Set locales
  command: "localectl set-locale {{ locale }}"

- name: Set keymap
  command: "localectl set-keymap {{ keymap }}"
