---
- name: Enable firewalld service
  ansible.builtin.systemd:
    name: firewalld.service
    state: started
    enabled: true

- name: Enable NetworkManager service
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: started
    enabled: true
