---
- name: Clone user dotfiles
  ansible.builtin.git:
    repo: https://github.com/kaniville/linux-dotfiles
    dest: /tmp/dotfiles
    clone: yes
    update: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  ansible.posix.synchronize:
    src: /tmp/dotfiles/
    dest: "/home/{{ user.name }}"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=src"
      - "--exclude=LICENSE"
      - "--exclude=README.md"
  become_user: "{{ user.name }}"

- name: Install ranger devicons
  ansible.builtin.git:
    repo: https://github.com/alexanderjeurissen/ranger_devicons.git
    dest: "/home/{{ user.name }}/.config/ranger/plugins/ranger_devicons"
    clone: yes
    update: yes
  become_user: "{{ user.name }}"

- name: Install packer nvim
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim.git
    dest: "/home/{{ user.name }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    clone: yes
    update: yes
  become_user: "{{ user.name }}"
