---
- name: Create builder user
  ansible.builtin.user:
    name: "{{ aur.user }}"
    state: present
    create_home: yes

- name: Set builder permission
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ aur.user }}"
    content: "{{ aur.user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    force: yes

- name: Install AUR helper
  kewlfft.aur.aur:
    use: makepkg
    name: "{{ aur.helper }}"
    state: present
  ignore_errors: true
  become_user: "{{ aur.user }}"
