---
- name: Import sudoers
  ansible.builtin.import_tasks:
    file: sudoers.yml
  tags: sudo

- name: Import usbguard
  ansible.builtin.import_tasks:
    file: usbguard.yml
  tags: usbguard

- name: Import snapshot script
  ansible.builtin.import_tasks:
    file: snapshot.yml
  tags: snapshot

- name: Import Firejail
  ansible.builtin.import_tasks:
    file: firejail.yml
  tags: firejail
