---
- name: Set GDM keyboard
  ansible.builtin.command: "localectl set-x11-keymap {{ locale.keymap }}"

- name: Enable GDM service
  ansible.builtin.systemd:
    name: gdm.service
    state: started
    enabled: true