---
- hosts: localhost
  become: yes

  tasks:
    - ansible.builtin.import_role:
        name: 01-core
      tags: core

    - ansible.builtin.import_role:
        name: 02-system
      tags: system

    - ansible.builtin.import_role:
        name: 03-desktop
      tags: desktop

    - ansible.builtin.import_role:
        name: 04-user
      tags: user
