---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - ansible.builtin.import_role:
        name: 01-common
      tags: common

    - ansible.builtin.import_role:
        name: 02-system
      tags: system

    - ansible.builtin.import_role:
        name: 03-users
      tags: users

    - ansible.builtin.import_role:
        name: 04-configuration
      tags: configuration

    - ansible.builtin.import_role:
        name: 05-desktop
      tags: desktop

    - ansible.builtin.import_role:
        name: 06-services
      tags: services
