---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - ansible.builtin.import_role:
        name: core
      tags: core

    - ansible.builtin.import_role:
        name: user
      tags: user

    - ansible.builtin.import_role:
        name: system
      tags: system

    - ansible.builtin.import_role:
        name: security
      tags: security

    - ansible.builtin.import_role:
        name: desktop
      tags: desktop

    - ansible.builtin.import_role:
        name: development
      tags: development

    - ansible.builtin.import_role:
        name: network
      tags: network
