---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - ansible.builtin.import_role:
        name: 01-core
      tags: core

    - ansible.builtin.import_role:
        name: 02-system
      tags: system

    - ansible.builtin.import_role:
        name: 03-security
      tags: security

    - ansible.builtin.import_role:
        name: 04-user
      tags: user

    - ansible.builtin.import_role:
        name: 05-desktop
      tags: desktop

    - ansible.builtin.import_role:
        name: 06-development
      tags: development

    - ansible.builtin.import_role:
        name: 07-network
      tags: network
