---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - ansible.builtin.import_role:
        name: 01-core
      tags: core

    - ansible.builtin.import_role:
        name: 02-users
      tags: users

    - ansible.builtin.import_role:
        name: 03-system
      tags: system

    - ansible.builtin.import_role:
        name: 04-tools
      tags: tools

    - ansible.builtin.import_role:
        name: 05-desktop
      tags: desktop

    - ansible.builtin.import_role:
        name: 06-applications
      tags: applications
