---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: (LIVE) Core configuration & packages
      ansible.builtin.import_role:
        name: 01-core
      tags:
        - LIVE
        - core

    - name: (LIVE) Install system packages & configure the system
      ansible.builtin.import_role:
        name: 02-system
      tags:
        - LIVE
        - system

    - name: (ROOT) Configure tools
      ansible.builtin.import_role:
        name: 03-config
      tags:
        - ROOT
        - config

    - name: (ROOT) Installation & configuration of the desktop
      ansible.builtin.import_role:
        name: 04-desktop
      tags:
        - ROOT
        - desktop

    - name: (ROOT) User creation & configuration
      ansible.builtin.import_role:
        name: 05-users
      tags:
        - ROOT
        - users

    - name: (USER) Installation of dotfiles
      ansible.builtin.import_role:
        name: 06-homedir
      tags:
        - USER
        - homedir
