---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: (LIVE) Core configuration & packages
      ansible.builtin.import_role:
        name: 01-core
      tags:
        - LIVE
        - 01-core

    - name: (LIVE) Install system packages & configure the system
      ansible.builtin.import_role:
        name: 02-system
      tags:
        - LIVE
        - 02-system

    - name: (ROOT) Configure tools
      ansible.builtin.import_role:
        name: 03-config
      tags:
        - ROOT
        - 03-config

    - name: (ROOT) Installation & configuration of the desktop
      ansible.builtin.import_role:
        name: 04-desktop
      tags:
        - ROOT
        - 04-desktop

    - name: (ROOT) User creation & configuration
      ansible.builtin.import_role:
        name: 05-users
      tags:
        - ROOT
        - 05-users

    - name: (USER) Installation of dotfiles
      ansible.builtin.import_role:
        name: 06-homedir
      tags:
        - USER
        - 06-homedir
