---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: (LIVE) Core configuration & packages
      ansible.builtin.import_role:
        name: 01-core
      tags:
        - LIVE
        - core

    - name: (LIVE) Install system packages & configure the system
      ansible.builtin.import_role:
        name: 02-system
      tags:
        - LIVE
        - system

    - name: (ROOT) Starting Services
      ansible.builtin.import_role:
        name: 03-services
      tags:
        - ROOT
        - services

    - name: (ROOT) Install & configure tools
      ansible.builtin.import_role:
        name: 04-tools
      tags:
        - ROOT
        - tools

    - name: (ROOT) Installation & configuration of the desktop
      ansible.builtin.import_role:
        name: 05-desktop
      tags:
        - ROOT
        - desktop

    - name: (ROOT) User creation & configuration
      ansible.builtin.import_role:
        name: 06-users
      tags:
        - ROOT
        - users

    - name: (USER) Installation of dotfiles
      ansible.builtin.import_role:
        name: 07-homedir
      tags:
        - USER
        - homedir
