---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - ansible.builtin.import_role:
        name: common
      tags: common

    - ansible.builtin.import_role:
        name: users
      tags: users

    - ansible.builtin.import_role:
        name: system
      tags: system

    - ansible.builtin.import_role:
        name: desktop
      tags: desktop
