---
- hosts: localhost
  become: true
  tags: SYSTEM

  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: system/00-packages
      tags:
        - LIVE
        - packages

    - name: Install locales
      ansible.builtin.import_role:
        name: system/01-locale
      tags:
        - LIVE
        - locale

    - name: Install bootloader & kernel
      ansible.builtin.import_role:
        name: system/02-boot
      tags:
        - LIVE
        - boot

    - name: Create & configure users
      ansible.builtin.import_role:
        name: system/03-users
      tags:
        - LIVE
        - users

    - name: Configure system
      ansible.builtin.import_role:
        name: system/04-configuration
      tags:
      - LIVE
      - configuration

    - name: Start services
      ansible.builtin.import_role:
        name: user/00-services
      tags:
        - BOOT
        - services

    - name: Hardened the system
      ansible.builtin.import_role:
        name: system/06-security
      tags:
        - BOOT
        - security

    - name: Configure Gnome
      ansible.builtin.import_role:
        name: system/07-gnome
      tags:
        - BOOT
        - gnome
