---
flatpak_packages:
  # Desktop
  - org.gnome.eog
  - org.kde.okular
  - org.gnome.Calculator
  - io.mpv.Mpv
  - org.pulseaudio.pavucontrol
  - org.gnome.seahorse.Application

  # Tools
  - org.libreoffice.LibreOffice
  - org.gimp.GIMP
  - org.filezillaproject.Filezilla
  - org.guitarix.Guitarix
  - org.keepassxc.KeePassXC
  - com.github.tchx84.Flatseal

  # Games
  - com.valvesoftware.Steam
  - com.mojang.Minecraft
  - sh.ppy.osu

  # Web browser
  - org.mozilla.firefox
  - org.chromium.Chromium

  # Extra
  - com.spotify.Client
  - com.discordapp.Discord

systemd_services:
  - podman.service
  - battery-notifier.timer

libraries:
  python:
    - psutil
    - i3ipc
    - pillow
