---
flatpak_packages:
  # Desktop
  - org.gnome.Loupe
  - org.gnome.Evince
  - io.mpv.Mpv
  - io.bassi.Amberol
  - org.gnome.Calendar

  # System
  - com.mattjakeman.ExtensionManager
  - ca.desrt.dconf-editor
  - org.gnome.seahorse.Application
  - com.github.tchx84.Flatseal

  # Tools
  - org.gnome.Boxes
  - org.gnome.Characters
  - org.libreoffice.LibreOffice
  - org.gimp.GIMP
  - org.keepassxc.KeePassXC
  - com.vixalien.sticky

  # Games
  - com.valvesoftware.Steam
  - com.mojang.Minecraft
  - sh.ppy.osu

  # Web browser
  - org.mozilla.firefox
  - org.chromium.Chromium

  # Extra
  - com.spotify.Client
  - com.discordapp.Discord
  - ar.com.tuxguitar.TuxGuitar
