---
- name: Import packages
  ansible.builtin.import_tasks:
    file: packages.yml
  tags: packages

- name: Import services
  ansible.builtin.import_tasks:
    file: services.yml
  tags: services

- name: Import apparmors profiles
  ansible.builtin.import_tasks:
    file: apparmor.yml
