---
terminal_packages:
  # Terminal
  - fish
  - htop
  - ranger
  - wl-clipboard

  # Informations
  - man-db
  - neofetch

  # Development
  - neovim
  - ripgrep
  - npm
  - python-pip
  - android-tools

applications_packages:
  # Terminal/File manager
  - alacritty
  - nautilus

  # android
  - scrcpy

  # Sync
  - syncthing

  #TCP/IP
  - wireshark-qt
