---
additional_packages:
  # Terminal
  - fish
  - ranger
  - android-tools
  - wl-clipboard

  # Development
  - neovim
  - npm
  - python-pip

  # Share
  - syncthing

  # GUI
  - wireshark-qt
  - scrcpy
