---
- name: Check if user is created
  command: "getent passwd {{ user.name }}"
  register: user_exists
  ignore_errors: true

- name: Add user
  community.general.homectl:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    memberof: "{{ user.groups }}"
    shell: "{{ user.shell }}"
    storage: "luks"
  when: user_exists.rc != 0
