---
- name: Import packages
  ansible.builtin.import_tasks:
    file: packages.yml
  become: true
  tags: packages

- name: Import Kernel modules
  ansible.builtin.import_tasks:
    file: sysctl.yml
  become: true
  tags: sysctl

- name: Import Udev rules
  ansible.builtin.import.tasks:
    file: udev.yml
  become: true
  tags: udev

- name: import gdm configuration
  ansible.builtin.import_tasks:
    file: locale.yml
  become: true
  tags: locale

