---
- name: Enable system services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
  loop: "{{ services.system }}"
  become: true
  tags: systemd,services

- name: Enable user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  loop: "{{ services.user }}"
  tags: systemd,services