---
- name: Install user dotfiles
  ansible.builtin.copy:
    src: dotfiles/
    dest: "/home/{{ user.name }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Install ranger devicons
  ansible.builtin.git:
    repo: https://github.com/alexanderjeurissen/ranger_devicons.git
    dest: "/home/{{ user.name }}/.config/ranger/plugins/ranger_devicons"
    clone: yes
    update: yes
  become_user: "{{ user.name }}"

- name: Install packer nvim
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim.git
    dest: "/home/{{ user.name }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    clone: yes
    update: yes
  become_user: "{{ user.name }}"
