---
- name: Import user
  ansible.builtin.import_tasks:
    file: user.yml

- name: Import services
  ansible.builtin.import_tasks:
    file: services.yml
  tags: services

- name: Import AUR helper
  ansible.builtin.import_tasks:
    file: aur.yml
  tags: packages
