---
- name: Import locale
  ansible.builtin.import_tasks:
    file: locale.yml
  become: true
  tags: locale

- name: Import packages
  ansible.builtin.import_tasks:
    file: packages.yml
  become: true
  tags: packages

- name: Import system services
  ansible.builtin.import_tasks:
    file: services.yml
  become: true
  tags: services
