---
- name: Import packages
  ansible.builtin.import_tasks:
    file: packages.yml
  become: true
  tags: packages

- name: Import locale
  ansible.builtin.import_tasks:
    file: locale.yml
  become: true
  tags: locale

- name: Import usbguard
  ansible.builtin.import_tasks:
    file: usbguard.yml
  become: true
  tags: usbguard
