---
- name: Import packages
  ansible.builtin.import_tasks:
    file: packages.yml
  tags: packages

- name: Import services
  ansible.builtin.import_tasks:
    file: services.yml
  tags: services

- name: Import systemd config
  ansible.builtin.import_tasks:
    file: systemd.yml
  tags: systemd
